/*
Given a string containing of ‘0’, ‘1’ and ‘?’ wildcard characters, generate all binary strings that can be formed by replacing each wildcard character by ‘0’ or ‘1’.

Input Format
The first line of input contains a single integer T denoting the number of test cases. Then T test cases follow. Each test case consist of two lines. The first line of each test case consists of a string S.

Constraints
1 ≤ T ≤ 60 1 ≤ length of string S ≤ 30

Output Format
Print all binary string that can be formed by replacing each wildcard character separated by space.

Sample Input
1
1??0?101

Sample Output
10000101 10001101 10100101 10101101 11000101 11001101 11100101 11101101

Explanation
For the Given test case, 10000101 can be generated by replacing wildcard character from 1??0?101 by 0s.
*/

#include<bits/stdc++.h>
using namespace std;

void fxn(string s, int i, int n, vector<string> &temp) {
    
    if(i == n) {
        temp.push_back(s); 
        return;
    }
    
    
    if(s[i] == '?') {
        s[i] = '0';  
        fxn(s, i+1, n, temp);  
        
        s[i] = '1';  
        fxn(s, i+1, n, temp);  
    } else {
        
        fxn(s, i+1, n, temp);
    }
}

int main() {
    int t;
    cin >> t;  
    
    while(t--) {
        string s;
		cin >> s;
        int n = s.length();
        vector<string> temp;
        
        fxn(s, 0, n, temp);  
		for(int i = 0; i < temp.size(); i++) {
			cout << temp[i] << " ";
		}
		
        cout << endl;  
    }

    return 0;
}
